# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 12:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('houses', '0002_auto_20170214_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('phone', models.CharField(max_length=50, verbose_name='phone')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.House', verbose_name='house')),
            ],
        ),
    ]
